katanemo/archgw

arch/tools/poetry.lock
model_server/poetry.lock

```
Installing dependencies from lock file
pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.
Error installing model server dependencies: Command '['poetry', 'install', '--no-cache']' returned non-zero exit status 1.
```

update lock file

---

crates/prompt_gateway/src/filter_context.rs
crates/prompt_gateway/src/http_context.rs
crates/prompt_gateway/src/stream_context.rs
crates/prompt_gateway/tests/integration.rs

Updated arch gateway code to not panic if embedding server is not up yet. Rather it will keep on trying.
This code change fixes https://github.com/katanemo/arch/issues/247 and https://github.com/katanemo/arch/issues/243

retry embeddings fetch

---

crates/common/src/lib.rs
crates/common/src/pii.rs
crates/llm_gateway/src/stream_context.rs
crates/prompt_gateway/src/http_context.rs

fixes https://github.com/katanemo/arch/issues/234
now log line should look like this
```
archgw-1  | [2024-11-08 07:29:15.598][39] ... req_headers=[... ("authorization", "Bearer ***") ...]
```

obfuscate auth header

---

demos/weather_forecast/arch_config.yaml
demos/weather_forecast_signoz/arch_config.yaml

mistral keys shouldn't really exist in the weather forecast demos.

removing hard depdency on mistral keys in weather forecast demos

---

.github/workflows/rust_tests.yml
arch/Dockerfile
arch/README.md
arch/docker-compose.dev.yaml
crates/llm_gateway/tests/integration.rs
crates/prompt_gateway/tests/integration.rs
demos/hr_agent/Dockerfile
demos/network_agent/Dockerfile
demos/shared/chatbot_ui/Dockerfile
model_server/Dockerfile

wasm-wasi32 target is deprated and will be removed in rust 1.84. Updating our build system to use wasm-wasi32p1 which is the recommendation. See [here for detail](https://blog.rust-lang.org/2024/04/09/updates-to-rusts-wasi-targets.html).
Also update envoy to 1.32 and python to 3.12.

update rust toolchain to 1.82

---

README.md

we no longer support 3.10
```
(venv) ➜  intelligent-prompt-gateway git:(main) ✗ archgw build
2024-11-25 15:27:25,559 - cli.main - INFO - Starting archgw cli version: 0.1.0
Building archgw image...
[+] Building 26.8s (30/30) FINISHED                                                                                                                                                                                      docker:desktop-linux
...
Current Python version (3.10.15) is not allowed by the project (>=3.12).
Please change python executable via the "env use" command.
...
```

update readme with python version

---

arch/arch_config_schema.yaml
demos/hr_agent/arch_config.yaml

without this change you'd see following error,
```
2024-11-25 17:32:21,008 - cli.main - INFO - Validating /Users/adilhafeez/src/intelligent-prompt-gateway/demos/hr_agent/arch_config.yaml
Error validating arch_config file: /Users/adilhafeez/src/intelligent-prompt-gateway/demos/hr_agent/arch_config.yaml, error: Additional properties are not allowed ('enum' was unexpected)
2024-11-25 17:32:21,019 - cli.main - INFO - Exiting archgw up: validation failed
```
fixes https://github.com/katanemo/archgw/issues/212

add schema change to use enum in arch_config

---

demos/llm_routing/run_demo.sh

**What**
- add `run_demo.sh` file for llm_routing demo 
**Why**
- It's mentioned in the [README](https://github.com/katanemo/archgw/tree/main/demos/llm_routing) but It's missing.

Add run_demo.sh for llm_routing demo

---

arch/arch_config_schema.yaml
arch/envoy.template.yaml
demos/currency_exchange_ollama/arch_config.yaml
docs/source/concepts/llm_provider.rst

Add support for using custom llm that are served through https protocol.

add support for custom llm with ssl support

---

docs/source/guides/observability/tracing.rst

This PR adds a new section to the Arch documentation, under the Observability -> Tracing section, to describe the integration with Langtrace, an observability tool specifically designed for large language models (LLMs).
This section includes:
- Introduction to Langtrace: A brief overview of Langtrace and its capabilities.
- Integration steps: Clear instructions on how to integrate Langtrace with Arch, including installation and tracing requests.
- Example code: A Python code snippet demonstrating how to trace requests using the Langtrace SDK.
Below is a screenshot of what a sample request looks like on the Langtrace dashboard:

Add Langtrace as a supported observability tool

---

arch/arch_config_schema.yaml
arch/envoy.template.yaml
arch/tools/cli/config_generator.py
demos/currency_exchange/arch_config.yaml

If port is not specified in endpoint then port will be inferred from protocol. For example in following arch_config we didn't specify port but the arch gateway inferred port 443 from protocol def,
arch_config.yaml
```
...
endpoints:
frankfurther_api:
endpoint: api.frankfurter.dev
protocol: https
...
```
envoy.yaml
```
...
- name: frankfurther_api
connect_timeout: 5s
type: LOGICAL_DNS
dns_lookup_family: V4_ONLY
lb_policy: ROUND_ROBIN
load_assignment:
cluster_name: frankfurther_api
endpoints:
- lb_endpoints:
- endpoint:
address:
socket_address:
address: api.frankfurter.dev
port_value: 443
hostname: api.frankfurter.dev
...
```

Infer port from protocol if port is not specified and add ability to override hostname in clusters def

---

arch/tools/cli/core.py
arch/tools/cli/docker_cli.py

- "dokcer inspect" doesn't return State/Status if container is not running
- "docker remove" is not a command supported by podman
- "docker logs" expect -f to be passed before container name

Fix compatibility issues with podman system

---

arch/tools/cli/docker_cli.py

Adding `--type=container` ensures `docker inspect` targets containers specifically, preventing conflicts with images in Podman.
Related discussion: https://github.com/katanemo/archgw/issues/417#issuecomment-2682369098

fix: add --type=container to docker inspect to prevent Podman conflicts

---

arch/tools/cli/core.py
crates/common/src/api/open_ai.rs
crates/llm_gateway/src/stream_context.rs
crates/llm_gateway/tests/integration.rs

When we start archgw gateway through cli the cli waits for gateway to become healthy. We have published healthz endpoint for prompt_gateway but for llm_gateway it never existed. So when a user started only llm_gateway then health check would never pass.

add health check endpoint for llm gateway

---

.github/workflows/docker-push-main.yml
.github/workflows/docker-push-release.yml

Right now we publish docker images for all commits that go on main. This change will start publishing images for releases. This will keep a publish history of our docker images by release version. Eventually we will update our CLI's to use these pin'ed versions whenever we publish a new release.
This is the view of repository right now,
https://hub.docker.com/repository/docker/katanemo/archgw/general
After this change we should see per arch and multi-arch docker image for each release. For example for release 0.2.3 you'd see following images,
- 0.2.3-amd64
- 0.2.3-arm64
- 0.2.3

publish docker release images

---

CONTRIBUTING.md

This PR fixes the Discord invite link in the contributing.md file.

Update discord server invite url

---

arch/arch_config_schema.yaml
arch/tools/cli/config_generator.py
demos/use_cases/llm_routing/arch_config.yaml

before,
```
- name: deepseek
access_key: $DEEPSEEK_API_KEY
provider_interface: openai
model: deepseek-reasoner
endpoint: api.deepseek.com
protocol: https
port: 443
```
after
```
- name: deepseek
access_key: $DEEPSEEK_API_KEY
provider_interface: openai
model: deepseek-reasoner
base_url: https://api.deepseek.com/
```

start using base_url in place of endpoint

---

README.md
arch/Dockerfile
crates/common/src/http.rs
crates/common/src/ratelimit.rs
crates/common/src/tokenizer.rs
crates/llm_gateway/src/stream_context.rs
crates/llm_gateway/tests/integration.rs
crates/prompt_gateway/src/http_context.rs
crates/prompt_gateway/src/stream_context.rs
crates/prompt_gateway/tests/integration.rs

Use info and debug logs appropriately. Previously most logs were logged under debug. This change fixes that and information logs are appropriately tagged also updated few log lines to have warn type.
Also sets info as default log for wasm filter.
Here is sample log after the log update,
```
[2025-03-26 18:32:01.350][26][info] prompt_gateway: on_http_request_body: sending request to model server
[2025-03-26 18:32:01.851][26][info] prompt_gateway: on_http_call_response: model server response received
[2025-03-26 18:32:01.852][26][info] prompt_gateway: on_http_call_response: dispatching api call to developer endpoint: weather_forecast_service, path: /weather, method: POST
[2025-03-26 18:32:01.882][26][info] prompt_gateway: on_http_call_response: developer api call response received: status …
```

Use better logs

---

arch/envoy.template.yaml
arch/tools/cli/config_generator.py
arch/tools/cli/docker_cli.py
crates/brightstaff/src/handlers/chat_completions.rs
crates/brightstaff/src/main.rs
crates/brightstaff/src/router/llm_router.rs
crates/brightstaff/src/router/router_model.rs
crates/brightstaff/src/router/router_model_v1.rs
crates/common/src/api/hallucination.rs
crates/common/src/api/open_ai.rs
crates/llm_gateway/src/stream_context.rs
crates/prompt_gateway/src/http_context.rs
crates/prompt_gateway/src/stream_context.rs
crates/prompt_gateway/tests/integration.rs
demos/use_cases/preference_based_routing/arch_config.yaml
demos/use_cases/preference_based_routing/hurl_tests/simple.hurl
demos/use_cases/preference_based_routing/hurl_tests/simple_stream.hurl

Adds support for json based content in message struct. For example you can now add text blocks,
```
"messages": [
{
"role": "user",
"content": [
{
"type": "text",
"text": "What city do you want to know the weather for?"
}
]
}
]
```
here is another example,
```
"messages": [
{
"role": "user",
"content": [
{
"type": "text",
"text": "What city do you want to know the weather for?"
},
{
"type": "text",
"text": "hello world"
}
]
}
]
```

Add support for json based content types in Message

---

demos/use_cases/llm_routing/arch_config.yaml

updated llm_routing demo to add claude-4 in list of llm_providers
```
$ curl -XPOST -v localhost:12000/v1/chat/completions -H 'content-type: application/json' -d '{"stream": false, "messages": [{"role": "user","content": "hello"}]}' | jq .
...
{
"id": "msg_01NnyBz8ijqtZEMiD6cdgzEL",
"choices": [
{
"finish_reason": "stop",
"index": 0,
"message": {
"role": "assistant",
"content": "Hello! How are you doing today? Is there anything I can help you with?"
}
}
],
"created": 1748020705,
"model": "claude-sonnet-4-20250514",
"object": "chat.completion",
"usage": {
"completion_tokens": 20,
"prompt_tokens": 8,
"total_tokens": 28
}
}
```

add claude-4 in llm_routing demo

---

crates/brightstaff/src/lib.rs
crates/brightstaff/src/main.rs
crates/brightstaff/src/router/llm_router.rs
crates/brightstaff/src/router/router_model_v1.rs
crates/brightstaff/src/utils/mod.rs
crates/brightstaff/src/utils/tracing.rs
crates/common/src/tokenizer.rs

In this code change trimming happens where we keep most recent messages and start trimming old conversation until total message token size is below max token size supported by router model.
One exception is that if we are down to single message then we will keep the conversation even if it exceed the max token count.

trim conversation if it exceed max limit of what router model can handle

---

arch/envoy.template.yaml
arch/tools/cli/docker_cli.py
crates/brightstaff/src/handlers/chat_completions.rs
crates/brightstaff/src/handlers/mod.rs
crates/brightstaff/src/handlers/models.rs
crates/brightstaff/src/main.rs
crates/common/src/api/open_ai.rs
demos/use_cases/llm_routing/arch_config.yaml
demos/use_cases/llm_routing/docker-compose.yaml

This code change adds /v1/models endpoint. This is needed by openwebui to show list of supported models.
Another noticeable change in this PR is to use model name from chat message if we cannot find model name from arch-router.

add support for openwebui

---

arch/Dockerfile

Fixes docker build warning for casing.
WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)                                                                                                                                                                         WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 11)                                                                                                                                                                       
WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 14)

Update Dockerfile to fix warnings

---

arch/arch_config_schema.yaml
arch/tools/cli/config_generator.py
crates/brightstaff/src/main.rs
crates/brightstaff/src/router/llm_router.rs
crates/common/src/configuration.rs
crates/llm_gateway/src/stream_context.rs
demos/use_cases/preference_based_routing/arch_config.yaml
demos/use_cases/preference_based_routing/arch_config_local.yaml
demos/use_cases/preference_based_routing/test_router_endpoint.rest

- make arch-router definition in llm_providers optional
- automatically add arch-router if usage is defined in llm_providers
- make api_key optional for arch type provider

make arch-router cluster optional

---

model_server/src/cli.py

If you install `archgw` / `archgw_modelserver` with `uv` (`uv tool install archgw_modelserver` or `uv tool install --editable ./model_server` for local dev), then `python` may not be an executable on the system. `sys.executable` should behave the same way if you're activating a venv, but also play nicely with `uv tool` workflows

archgw_model_server: use sys.executable for uv tool install compat
