katanemo/archgw

model_server/app/cli.py
model_server/app/tests/test_cli_stop_server.py

PR to fix https://github.com/katanemo/arch/issues/207
Solution:
Increase timeout to 20s
Kill all children of the process
Kill all pids on port 51000

fix model server stop process

---

crates/prompt_gateway/src/stream_context.rs

chore: update stream_context.rs

---

arch/arch_config_schema.yaml
arch/build_filter_image.sh
arch/tools/poetry.lock
arch/tools/pyproject.toml
build_filter_image.sh
crates/prompt_gateway/src/stream_context.rs
demos/weather_forecast/arch_config.yaml
e2e_tests/test_prompt_gateway.py
model_server/pyproject.toml

Updated code to accept prompt_guard and updated e2e tests to validate prompt_guards
fixes #274

use fix prompt guards

---

demos/shared/grafana/dashboards/envoy_overview.json
demos/shared/prometheus/prometheus.yaml

Signed-off-by: Peter Jausovec <peter.jausovec@solo.io>

update alertmanager version to v2, remove the merge artifacts

---

demos/weather_forecast/README.md

Replaced incorrect demo stopping guide with correct, updated one

fix the README for the weather_forecasting demo

---

.github/workflows/e2e_archgw.yml
.github/workflows/e2e_model_server.yml
.github/workflows/e2e_test_demos.yml
.github/workflows/e2e_tests.yml
.github/workflows/model-server-tests.yml

release of poetry 2.0.0 broke our tests - https://github.com/python-poetry/poetry/releases/tag/2.0.0
temporarily fixes https://github.com/katanemo/archgw/issues/359

pin poetry to 1.8.5

---

arch/tools/cli/core.py
arch/tools/cli/utils.py

(venv) ➜  currency_exchange git:(main)  sh run_demo.sh
.env file already exists. Skipping creation.
...
2025-01-08 13:59:42,942 - cli.utils - INFO - Default docker socket /var/run/docker.sock not found, using unix:///Users/adilhafeez/.docker/run/docker.sock
...
fixes https://github.com/katanemo/archgw/issues/351
fixes https://github.com/katanemo/archgw/issues/352 (not needed anymore)

use per user docker socket if system docker socket doesn't exist

---

archgw.code-workspace

https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github

add github pull request extension in vscode

---

demos/shared/honeycomb/Dockerfile
demos/shared/honeycomb/otel-collector-config.yaml
demos/weather_forecast/docker-compose-honeycomb.yaml
demos/weather_forecast/run_demo.sh

Just quickly updated demo to have a honeycomb option, works similar to logfire and this what a honeycomb trace looks like.

add in honeycomb support for weather-forecast demo

---

crates/llm_gateway/src/stream_context.rs

When using ollama token count was not coming in resulting in token count and other metrics to show up as zero. This was not causing tracing to break.

When using ollama token count was not coming in

---

.github/workflows/docker-push.yml

Publish both arm64 and amd64 in docker on main

---

README.md
demos/use_cases/spotify_bearer_auth/arch_config.yaml
demos/use_cases/spotify_bearer_auth/docker-compose.yaml

Plus I made some minor formatting changes to our readme to follow like more traditional repos where there is a TOC

Fixing relative link to the shared chatbotui in the spotify demo, and add references to it in the README

---

crates/llm_gateway/src/stream_context.rs
crates/llm_gateway/tests/integration.rs
demos/use_cases/llm_routing/arch_config.yaml

add demo for deepseek

---

model_server/src/core/function_calling.py
model_server/src/core/utils/hallucination_utils.py
model_server/src/main.py
model_server/tests/core/test_function_calling.py

modify the hallucination check
1. Remove tool_call check, only check parameter value as tool call is not a single token anymore
2. Fix multi tools hallucination bug

add hallucination modification

---

docs/source/concepts/llm_provider.rst

docs: update llm_provider.rst

---

docs/source/build_with_arch/rag.rst

This PR deletes a typo in the documentation

remove typo

---

README.md
demos/samples_python/network_switch_operator_agent/README.md
demos/samples_python/weather_forecast/README.md
docs/source/concepts/prompt_target.rst
docs/source/concepts/tech_overview/listener.rst
docs/source/concepts/tech_overview/model_serving.rst
docs/source/concepts/tech_overview/prompt.rst
docs/source/concepts/tech_overview/request_lifecycle.rst
docs/source/concepts/tech_overview/terminology.rst
docs/source/get_started/intro_to_arch.rst
docs/source/guides/agent_routing.rst
docs/source/resources/configuration_reference.rst
docs/source/resources/includes/arch_config_full_reference.yaml

Did a doc read through and figured I'd make some quick typo tweaks!

[chore] Tweak readme docs for minor nits

---

demos/samples_python/human_resources_agent/arch_config.yaml
demos/samples_python/human_resources_agent/docker-compose.yaml

We were using same port for both chatui and app_server which was causing conflict. This code change updates host port for app_server to 18083 and updates arch_config

use separate host port for chat ui and for app_server

---

README.md

sample output for currency exchange from readme.md,
```
✗ curl --header 'Content-Type: application/json' \
--data '{"messages": [{"role": "user","content": "what is exchange rate for gbp"}]}' \
http://localhost:10000/v1/chat/completions 2> /dev/null | jq ".choices[0].message.content"
"Based on the provided context, the exchange rate for GBP on April 29, 2025, is 0.74721. This means 1 USD is equivalent to 0.74721 GBP."
```
sample output for llm routing from readme.md,
```
curl --header 'Content-Type: application/json' \
--data '{"messages": [{"role": "user","content": "What is the capital of France?"}]}' \
http://localhost:12000/v1/chat/completions 2> /dev/null | jq '.choices[0].message.content'
"The capital of France is Paris."
```

update arch_config sample on readme to match with new format

---

arch/Dockerfile
arch/arch_config_schema.yaml
arch/envoy.template.yaml
arch/tools/cli/core.py
crates/common/src/api/open_ai.rs
crates/common/src/configuration.rs
crates/llm_gateway/src/stream_context.rs
demos/samples_python/weather_forecast/arch_config.yaml
demos/shared/test_runner/run_demo_tests.sh
demos/use_cases/llm_routing/arch_config.yaml

streaming response,
```
$ curl -XPOST -v localhost:12000/v1/chat/completions -H 'content-type: application/json' -d '{"stream": true, "messages": [{"role": "user","content": "hello"}]}'
* upload completely sent off: 67 bytes
< HTTP/1.1 200 OK
...
data: {"id":"msg_0154YmvDMbwK5MdnHbxpsQyp","choices":[{"index":0,"delta":{"role":"assistant"}}],"created":1747688012,"model":"claude-3-7-sonnet-latest","object":"chat.completion.chunk"}
data: {"type": "ping"}
data: {"id":"msg_0154YmvDMbwK5MdnHbxpsQyp","choices":[{"index":0,"delta":{"content":"Hello!"}}],"created":1747688012,"model":"claude-3-7-sonnet-latest","object":"chat.completion.chunk"}
data: {"id":"msg_0154YmvDMbwK5MdnHbxpsQyp","choices":[{"index":0,"delta":{"content":" How can I assist you today? …
```

add support for claude

---

arch/tools/cli/utils.py

stream access logs from docker container directly, this helps us remove dependency on mountaing archgw volume mount on host

update archgw logs file to stream access logs from container

---

crates/brightstaff/src/main.rs
crates/brightstaff/src/router/llm_router.rs
crates/brightstaff/src/router/router_model_v1.rs
crates/common/src/api/hallucination.rs
crates/common/src/api/open_ai.rs
crates/common/src/configuration.rs
crates/common/src/tokenizer.rs
crates/prompt_gateway/src/http_context.rs
crates/prompt_gateway/tests/integration.rs
demos/use_cases/preference_based_routing/arch_config.yaml
demos/use_cases/preference_based_routing/docker-compose.yaml
demos/use_cases/preference_based_routing/test_router_endpoint.rest

uses model https://huggingface.co/katanemo/Arch-Router-1.5B

update code to use new json based system prompt for routing

---

docs/source/concepts/llm_provider.rst

Code blocks missing from docs, fixed format issue

Fix code block formatting in LLM Provider documentation

---

arch/Dockerfile

Fixes cve by removing libpam (passwd, login, adduser won't work but we don't use them in container anyway so we should be good)

fix cve_2025-6020 by removing libpam
